#!/bin/sh

# A wrapper around the perl wrapper around ant.  Avoids assumptions of perl's
# location.

if [ "$PROJECT_HOME" = "" ]; then
  perl build.pl $*
else
  perl $PROJECT_HOME/install/build.pl $*
fi
